### ISSUE TITLE
Setup file doesn't seem to be compatible with Magento2

### ISSUE THREAD

**Issue by deepak-netwin** [Genmato/DemoProduct#1]
Hi,

I want to use this module to create a new product type. But when I checked the module folder I found that the setup file is placed under data/genmato_demoproduct_setup/data-install-1.1.0.php which doesn't seem to be compatible with Magento2. Can you please let me know for what purpose you added this mysql script? Is it really needed?

Thanks & Regards,
Deepak

**Comment by vkerkhoff** [comment]
This code is based on a early beta version and no longer updated, you can checkout https://github.com/Genmato/M2_Sample/releases/tag/0.8.4 this code is updated with the release version functionality.

**Comment by deepak-netwin** [comment]
That's great! Thanks.
Previous module was added the new product type but when I created a product with that type, It was not allowing me to add price and quantity. Are these issues fixed in the latest build?
